# .goreleaser.yaml - GoReleaser configuration file
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: &project_name "file_conversor"

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test -v ./...

# binary builds (.exe, etc.)
builds:
  - main: ./cmd/...
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

# archives (tar.gz, zip, etc.)
archives:
  - formats: [ tar.gz ]
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ zip ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}_{{ .Os }}-{{ if eq .Arch "amd64"
      }}x86_64{{ else }}{{ .Arch }}{{ end }}
    # wrap files in a directory inside the archive
    wrap_in_directory: false
    # include additional files in the archive (optional)
    files:
      - LICENSE*
      - NOTICE*
      - docs/*  
      - src: "*.md"
        dst: .
    # set executable permissions for all files in the archive (optional)
    builds_info:
      group: root
      owner: root
      mode: 755

# deb and rpm packages
nfpms:
  - vendor: &author "Andre Luiz Romano Madureira"
    homepage: &homepage "https://github.com/andre-romano/file_conversor"
    maintainer: &maintainer "Andre Luiz Romano Madureira <andre@noreply.github.com>"
    description: &summary "A multi-format file conversion tool (jpg, doc, mp4, xlsx, etc)."
    license: &license "Apache-2.0"
    bindir: /usr/bin
    formats:
      - deb
      - rpm

    # dependency packages (optional)
    dependencies:
      - ca-certificates

    # packages provided by this project (optional, but recommended for package managers to auto-detect executables)
    provides:
      - *project_name
      - &project_name_gui "file_conversor_gui"

    # OS dependencies (optional)
    # recommends:
    #   - libreoffice-headless

    # OS optional dependencies (optional)
    # suggests:
    #  - ffmpeg

    # include additional files in the package (optional)
    contents:
      - src: LICENSE*
        dst: /usr/share/doc/{{ .ProjectName }}/
        type: "config"

      - src: NOTICE*
        dst: /usr/share/doc/{{ .ProjectName }}/
        type: "config"

      - src: docs/*
        dst: /usr/share/doc/{{ .ProjectName }}/docs/
        type: "config"

      - src: configs/*
        dst: /etc/{{ .ProjectName }}/
        type: "config"

    # systemd service (optional — remove if not a daemon)
    # contents:
    #   - src: packaging/linux/myapp.service
    #     dst: /lib/systemd/system/myapp.service
    #     type: config
    #   - src: packaging/linux/myapp.conf
    #     dst: /etc/myapp/myapp.conf
    #     type: config|noreplace   # never overwrite user config on upgrade

    # pre/post install/remove scripts (optional)
    scripts:
      preinstall: "packaging/linux/preinstall.sh"
      postinstall: packaging/linux/postinstall.sh
      preremove: packaging/linux/preremove.sh
      postremove: packaging/linux/postremove.sh

    # RPM-specific
    rpm:
      # group is a required field for older RPM packages (for categorization in package managers)
      #   (it doesn't have a direct equivalent in DEB, so we set it to a generic value).
      group: Applications/System

    # deb-specific
    deb:
      lintian_overrides:
        - statically-linked-binary

# release notes (changelog)
changelog:
  use: github
  sort: asc
  abbrev: 20 # shorten commit SHAs to 20 chars 
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^[M|m]erge "
  groups:
    - title: "🚀 Features"
      regexp: "^feat"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^fix"
      order: 1
    - title: "⚡ Performance"
      regexp: "^perf"
      order: 2
    - title: "🔒 Security"
      regexp: "^sec"
      order: 3
    - title: "Other"
      order: 999
