@startuml
' skinparam classAttributeIconSize 0

' Example class diagram template
class MainClass {
    +attribute1: type
    -attribute2: type
'   ------------------------- 
    +method1(param: type): returnType
    -method2(): void
}

class HelperClass {
    +helperAttribute: type
'   ------------------------- 
    +helperMethod(): void
}

MainClass --> HelperClass : uses

'=======================
' BACKENDs
'=======================

abstract class Backend {
    -input: str
    -output: str
    -options: dict[str, str]
'   ------------------------- 
    +input(in_file_path: str): void
    +output(out_file_path: str): this
    +options(**kwargs: dict[str, str]): this    
}

class FFmpegBackend extends Backend {
    +derivedAttribute: type
    +interfaceMethod(): void
    +baseMethod(): void
}


@enduml
