name: Publish Chocolatey

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  PROJECT_NAME: file_conversor # Update with your project name
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          pip install pdm
          pdm install

      - name: Build with Chocolatey
        run: |
          pdm run invoke build-choco

      - name: Push to Chocolatey
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco apikey --key "${{ env.CHOCO_API_KEY }}" --source https://push.chocolatey.org/
          choco push "dist/${{ env.PROJECT_NAME }}*.nupkg" --source https://push.chocolatey.org/
        continue-on-error: false
