name: Publish Git Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  PROJECT_NAME: file_conversor # Update with your project name
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_exe:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necess치rio para ver todo o hist칩rico

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          pip install pdm
          pdm install

      - name: Create release notes
        run: |
          pdm run invoke git.release-notes

      - name: Build and check Installer .EXE
        run: |
          pdm run invoke inno.check

      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: release_notes
          path: RELEASE_NOTES.md
          retention-days: 7

      - name: Upload installer EXE
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: dist/*.exe
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build_exe
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necess치rio para o git-chglog ver todo o hist칩rico

      - name: Download installer EXE
        uses: actions/download-artifact@v4
        with:
          name: exe
          path: ./dist

      - name: Download release notes
        uses: actions/download-artifact@v4
        with:
          name: release_notes
          path: .

      - name: Check artifacts download
        run: |
          ls dist/*.exe || ( echo "dist/*.exe not found" ; exit 1 )
          ls RELEASE_NOTES.md || ( echo "RELEASE_NOTES.md not found" ; exit 1 )
        shell: bash

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md
          files: |
            dist/*
          draft: false
          prerelease: ${{ contains(github.ref, '-') }} # ignore versions with v*.*.*-*

